#ifndef HASHMAP_OPTIMISED_PRIME_NUMBERS_H
#define HASHMAP_OPTIMISED_PRIME_NUMBERS_H

const int NUM_PRIME_NUMBERS = 5761454;

extern const int PRIME_NUMBERS[NUM_PRIME_NUMBERS];

#endif //HASHMAP_OPTIMISED_PRIME_NUMBERS_H
